Makefile.am
NEWS
README
configure.ac
exits.h
fips.c
fips.h
rdrand_asm.S
rngd.8.in
rngd.c
rngd.h
rngd_entsource.c
rngd_entsource.h
rngd_linux.c
rngd_linux.h
rngd_rdrand.c
rngtest.1.in
rngtest.c
stats.c
stats.h
util.c

rng-tools has been dormant upstream for some time, and several patches with new features (fips support , rdrand support, bug fixes), have been carrried out of tree.  This branch brings upstream up to date with those features

New features

---

rngd.8.in
rngd.c
rngd.h
rngd_darn.c
rngd_entsource.c
rngd_linux.c
rngd_rdrand.c

rngd has gotten rather crufty in the last several years.  Features were bolted on without much care for user design or elegance. This branch seeks to clean some of that up.  Among them:
* Improvement of command line arguments (this breaks user scripts, but I feel is needed)
* consolidation of data structures
* consistent handling of entropy sources
* cleanup of log messages

do some refactoring and clean up of rngd

---

rngd_darn.c

Simpler and more correct.
Tested:
$ ./rngd --list
Failed to init entropy source 0: Hardware RNG Device
Failed to init entropy source 1: TPM RNG Device
Enabling power DARN rng support
Available entropy sources:
3: Power9 DARN Instruction RNG

Check darn hardware with getauxval(AT_HWCAP2) & PPC_FEATURE2_ARCH_3_00

---

.travis.yml
rngd_linux.c

need to fix up some build errors both in the code and in the travis setup to get automated builds to work

Travis fixes

---

.travis.yml
tests/rngtesturandom.sh
tests/rngtestzero.sh

Fixups for make check target scripts and travis ci integration

Tests debug

---

rngd_nistbeacon.c

fix some obvious bugs in the nistbeacon

Fix build warnings in nistbeacon

---

configure.ac

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>

configure.ac: fix typo

---

rngd.c
rngd_jitter.c
rngd_linux.c
rngd_nistbeacon.c

fixes issue https://github.com/nhorman/rng-tools/issues/57

Fix up some compile warnings

---

rngd.c
rngd_jitter.c

Allow rngd to stop trying to generate entropy in the middle of a cycle on receipt of an exit signal, as calls to the jitter library can take significant amounts of time

Early jitter exit

---

rngd.c
rngd.h
rngd_darn.c
rngd_entsource.c
rngd_jitter.c
rngd_nistbeacon.c
rngd_pkcs11.c
rngd_rdrand.c

Several commits to make the logging more clear, clean and human readable

Logging cleanup

---

.travis.yml
Makefile.am
configure.ac

Enhnace pkcs11 entropy source to look for opensc library in the proper path based on target arch at configure time

Default pkcs11

---

ChangeLog
configure.ac
fips.c
fips.h
rngd.8.in
rngd.c
rngd_jitter.c
rngd_nistbeacon.c

Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>

Fix typos found with codespell

---

rngd.service

This PR add systemd service file. It is not installed by default.
This PR also helps to reslove this https://github.com/dracutdevs/dracut/pull/791

Add systemd service file

---

.travis.yml
rngd.c
rngd_darn.c
rngd_jitter.c
rngd_linux.c
rngd_nistbeacon.c
rngd_rtlsdr.c

* Test installation in TravisCI
* Use proper format specifier
* Remove unused variables
* Fix variable is not initialized
* Fix compile error

Code improvements

---

configure.ac

Adding -lpthread so that jitterentropy check works properly

---

configure.ac

try to build with rtlsdr by default

---

ossl_helpers.c
rngd.h
rngd_darn.c
rngd_entsource.c
rngd_jitter.c
rngd_linux.c
rngd_nistbeacon.c
rngd_rdrand.c
rngd_rndr.c
rngd_rtlsdr.c
stats.c

This patchset suggests a number small fixes for warnings found in a covscan report.

A number of small fixes per a covscan report

---

rngd.c
rngd_jitter.c
tests/rngtestjitter.sh

Hello, Neil,
This is the sysconf() fix we were talking about. Also, I've included two smallest general fixes, since I assume you plan to merge this branch. The main onecpu fix looks good to me, if I may provide such kind of a review.

onecpu branch suggested fixes

---

configure.ac
rngd_jitter.c

fixing setaffinity call for non-linux platforms

Setaffinity

---

Makefile.am
configure.ac
rngd.c
rngd.h
rngd.service

So it can run as a non-privileged user thus increasing security.

Allow rngd process to drop privileges

---

rngd.8.in

And brush up whole page a little.

Update rngd man page

---

Makefile.am
configure.ac
rngd.8.in
rngd.c
rngd.h
rngd_entsource.h
rngd_jitter.c
rngd_qrypt.c

Fix jitter to time out on init if it takes to long (more than 5 seconds) to gather enough entropy during initialization

Jitter init

---

rngd.8.in
rngd.c
rngd.h
rngd_qrypt.c

Original discussion and review comments here: https://github.com/nhorman/rng-tools/pull/169

Qrypt entropy source improvements

---

rngd.8.in
rngd.c
rngd_linux.c

Change Linux poolsize to reflect modern kernels

---

rngd_jitter.c

sysconf(_SC_NPROCESSORS_ONLN) can actually return -1.
Add a check for this the same way as in rngd_notime_init().

Check return value of sysconf() calls

---

rngd_entsource.c

Add ssize_t r2 variable for write() return value.
Use retval variable solely as a boolean for the function return code.
Subtract TPM_GET_RNG_OVERHEAD from r after the check.
Fixes #210.

Refactor xread_tpm() code

---

rngd_jitter.c

Add a counter for a maximum number of errors. If it is reached, bail out. Reset the counter on successful read or write.
Add error handling to the jitter read loop. Restart a read on error, since there is nothing to write out.
Add error handling to the pipe write loop. Handle a special case of EBADF error, see 3e47faa for details.
Fixes #209.

Add error handling to jitter read and pipe write loops

---

rngd_jitter.c
tests/rngtestjitter.sh
tests/rngtesturandom.sh
tests/rngtestzero.sh

Add a NULL check for calloc() return values
