- Makefile.am
- configure.ac
- rngd.c
- rngd_darn.c
- rngd_entsource.h
Detect power arch build and enable support for DARN random number instruction.
If enabled, at runtime, detect available instruction support, and, if present,
use DARN to seed an AES encryption operation of a garbage buffer to generate
random data for use in adding entropy to kernel rng.
> Add power DARN instruction support

- rngd_entsource.c
When start-stop-daemon starts a rngd instance configured to use a tty
device as its entropy source, the application crashes due to not being
able to read from the entropy device. This is caused by
start-stop-daemon calling setsid() before executing rngd, which
disassociates the controlling terminal. When rngd attempts to open a
hardware entropy source that's a tty device, per POSIX rules, the
device becomes the controlling terminal for the process. Then rngd
calls daemon(), which internally calls setsid(), and consequently
disassociates the controlling terminal for the child. Meanwhile the
parent rngd process exits. This results in tty device hanging up. By
looking at the strace logs attached to the bug, it can be observed
that although the parent rngd process is able to read() from the …
> Fix rngd to open the entropy source with 'O_NOCTTY' flag

- rngd.8.in
According to rngd man page, the default value for the
'--fill-watermark' option is 2048 bits. However, upon examining
default_watermark() function in rngd_linux.c, it can be seen that this
is true for systems where poolsize cannot be obtained. In linux, the
pool size can be obtained by reading
'/proc/sys/kernel/random/poolsize'. If rngd is capable of reading the
proc entry, as it should be, then it sets the --fill-watermark value
to be 75% of the total pool size, typically 3072 bits.
Bug: https://bugs.gentoo.org/555094
> Fix the default '--fill-watermark' value in the man page

- rngd_nistbeacon.c
The members "frequency" and "timestamp" of struct nist_data_block are
defined as int and long, respectively. On x86_64, their sizes
correctly correspond to 4 and 8 bytes. However, on 32-bit x86
architectures, both int and long are defined as 4 bytes, causing the
digest verification to fail. Fix it by using uint32_t and uint64_t
explicitly.
> rngd_nistbeacon: fix the size of frequency and timestamp on x86_32

- rngd.c
When running as a daemon, a signal handler is installed to catch
SIGINT/SIGTERM. This handler sets a flag that's tested in the main
loop. However, rngd loops in update_kernel_random() as well, where
the flag was not tested.
This patch adds the check to update_kernel_random() so that the
daemon exits properly after receiving a SIGINT/SIGTERM signal.
https://sourceforge.net/p/gkernel/bugs/135/
Have been carrying this patch, taken from that sourceforge ticket, for a few years. It fixes rngd getting stuck on system shutdown until init/systemd kills it after the timeout.
> Check for signals in update_kernel_random()

- .gitmodules
- .travis.yml
- Makefile.am
- configure.ac
- rngd.c
- rngd.h
- rngd_entsource.h
- rngd_jitter.c
The CPU Jitter RNG noise source is added as a new generic noise source.
It requires the static CPU Jitter RNG library that can be obtained from
[1]. The static library can be pointed to using the configure option of
--with-libjitterentropy-prefix.
The CPU Jitter RNG noise source is extensively discussed at [1].
[1] http://www.chronox.de/jent.html
> Add Jitter entropy source

- rngd_jitter.c
The jent_read_entropy function returns negative error codes. Thus, the
ret variable must be signed.
Signed-off-by: Stephan Mueller <smueller@chronox.de>
> Catch negative error codes in xread_jitter

- rngd.c
This fixes a critical error in "do_loop" which prevented entropy source 0 (/dev/hwrng) from ever being used.
It also fixes a couple of off-by-one errors, and makes do_loop function more like it was intended (I think).
> rngd.c: fixed main loop logic, and a couple of off-by-one errors

- configure.ac
autoselection of rdrand/darn support should be made based on the cpu being
targeted, not the host on which you are building.  Since those rngs are
slected based on availabilty of cpu instruction where it will run, not
where it is being built.
> select rdrand/darn based on target cpu, not host cpu

- rngd_rdrand.c
Instead of failing RDRAND init if there is no AES method available, just disable
AES usage and log the fact that thats happening.
> rdrand: disable AES if no AES facility available

- rngd.c
- rngd.h
- rngd_jitter.c
large mutex protected critical paths with functions in them that had high latency and high cpu usage were causing extreme latency during shutdown of the daemon.  Fix it by removing the high latency calls from the critical path.
> shrink rngd critical paths

- Makefile.am
- configure.ac
Currently, rng-tools uses libjitterentropy built locally in this source
tree as a static library.  That is sub-optimal however, as jitterentropy
is an independently maintained project.  Ideally it would be nice to
instead load libjitterentropy as a DSO, which that project can build as.
This is the first of three steps toward moving in that direction:
1) Add support to check for and link against libjitterentropy.so, if
found on the host
2) Deprecate local building of jitterentropy as a static library
3) Remove support for building jitterentropy as a static library
This commit implements step 1.  If the configure script finds a local
copy of the jitterentropy source, it will build a static library from
it.  If not, then it will look for a local libjitterentropy.so.  If
found, it will link …
> Add support for detecting installed libjitterentropy.so

- Makefile.am
- configure.ac
Check for 'ar' as it is used for standard builds as well as jitterentropy
Export select variables when building the jitterentropy library
> Add cross-compile fixes

- rngd_jitter.c
@nhorman I'll leave the `sleep` initialization fix for you.
> Jitter: remove superfluous pthread_mutex_unlock

- rngd.c
- rngd.h
Keep track of elapsed time, don't count on alarm(1) for timing
Use first alarm(1) as t=0
Use bits instead of bytes
Various output text tweaks
Sample results:
Entropy rate:  5.408 Kbits/sec averaged over 18 iterations for  65.01 seconds
Entropy rate:  52.34 Kbits/sec averaged over 190 iterations for    275 seconds
Entropy rate:  2.678 Mbits/sec averaged over 15 iterations for  15.06 seconds
Entropy rate:  104.2 Mbits/sec averaged over 26 iterations for     26 seconds
Entropy rate:    126 Mbits/sec averaged over 26 iterations for     26 seconds
> Test Mode: various enhancements and tweaks

- rngd_rdrand.c
Make xread_drng obey the restrictions imposed by x86_rdrand_bytes.
Otherwise, problems can happen (e.g. the call to discard_initial_data results in a smashed stack, which is how I encountered this problem).
>  Obey restrictions on x86_rdrand_bytes usage 

- .gitmodules
- Makefile.am
- configure.ac
This is a pull request to remove the jitterentropy submodule from rng-tools.  The intent is to remove it and modify the configure script such that it search for the jitterentropy dso on the host system instead.
> Remove static

- rngd.c
- rngd_jitter.c
- rngd_linux.c
convert jitterentropy source to use a pipe to deliver entropy.  This reduces the read size from needing to iterate over an arbitrary number of thread buffers.
Also introduce some hysteresis to allow rngd to fill the kernel entropy pool without sleeping until it is full
> Simplify and improve performance of rngd and jitterentropy

- .travis.yml
- Makefile.am
- configure.ac
- rngd.8.in
- rngd.c
- rngd.h
- rngd_entsource.h
- rngd_opensc.c
- rngd_pkcs11.c
add support for openssl pkcs11 engines.  This entropy source allows access to opensc compliant smart card readers as entropy generators
> Pkcs11 support

- configure.ac
Use foreign instead of gnu in AM_INIT_AUTOMAKE otherwise autoreconf will
fail on:
Makefile.am: error: required file './README' not found
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix autoreconf

- tests/rngtesturandom.sh
the urandom test may fail periodically.  This occurs because
/dev/urandom is a 'best effort' source of random data, and may at times
be less random than expected.  When this occurs, don't fail, but rather
note the issue, and skip the test
> Don't fail on urandom test failures

- Makefile.am
- configure.ac
In function init_pkcs11_entropy_source(), there is a call to
ERR_reason_error_string(), which is defined in libcrypto. This causes
linking problems for rng-tools under certain configurations:
$ ./configure --disable-jitterentropy --without-nistbeacon --with-pkcs11
...
$ make
...
gcc     -pthread -g -O2 -pthread   -o rngd rngd-rngd.o rngd-rngd_entsource.o rngd-rngd_linux.o rngd-util.o  rngd-rngd_rdrand.o rdrand_asm.o   rngd-rngd_pkcs11.o librngd.a -lsysfs -lgcrypt -lsysfs  -lp11     -lgcrypt -lsysfs
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: rngd-rngd_pkcs11.o: undefined reference to symbol 'ERR_reason_error_string@@OPENSSL_1_1_0'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libcrypto.so.1.1: error adding …
> Make rngd_pkcs11.c explicitly link against -lcrypto

- configure.ac
- rdrand_asm.S
This pull request is to import yocto fixes for rng-tools 6.6
see here
https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-support/rng-tools
some of those changes came from gentoo
https://packages.gentoo.org/packages/sys-apps/rng-tools
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/rng-tools
> Import yocto fixes for 6.6

- rngd_jitter.c
Making the jitter entropy source a little less racy in the use of sched_yield by properly introducing pthread mutexes and signals
> Yield removal

- rngd_darn.c
darn is broken after the last changes, so fix it. Discovered by our multi-arch CI.
````
gcc -DHAVE_CONFIG_H -I.     -DDEFAULT_PKCS11_ENGINE=\"/usr/lib64/opensc-pkcs11.so\"   -I/usr/include/libxml2   -pthread -g -O2 -MT rngd-rngd_darn.o -MD -MP -MF .deps/rngd-rngd_darn.Tpo -c -o rngd-rngd_darn.o `test -f 'rngd_darn.c' || echo './'`rngd_darn.c
rngd_darn.c: In function ‘init_openssl’:
rngd_darn.c:81:2: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
81 |  memcpy(&iv_buf[0], &darn_val, sizeof(uint64_t));
|  ^~~~~~
rngd_darn.c:81:2: warning: incompatible implicit declaration of built-in function ‘memcpy’
rngd_darn.c:40:1: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
39 | #include "rngd_entsource.h"
+++ |+#include <string.h>
40 | …
```
> fix build on ppc64le

- rngd.c
When rngd is built without rtlsdr it segfaults at runtime.
```
./configure --without-nistbeacon --without-rtlsdr --without-libargp --disable-jitterentropy  --without-pkcs11
root@rpi4:/home/rng-tools# ./rngd -l
Entropy sources that are available but disabled
1: TPM RNG Device (tpm)
Available and enabled entropy sources:
0: Hardware RNG Device (hwrng)
[hwrng ]: Shutting down
[rtlsdr]: Shutting down
root@rpi4:/home/rng-tools# ./rngd -f -t -d
Initializing available sources
[hwrng ]: Initialized
Entering test mode...no entropy will be delivered to the kernel
Reading entropy from Hardware RNG Device
Reading entropy from RTLSDR software defined radio generator
Segmentation fault (core dumped)
```
```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000401f54 in do_loop (random_step=64) at rngd.c:667 …
```
> fix segfault when built without rtlsdr

- configure.ac
Add missing ',' to allow the user to explicitly disable or enable rtlsdr
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix --with-rtlsdr option

- rngd_jitter.c
Commit 0f184ea7e792427fb20afe81d471b565aee96f0b disambiguate the call to encrypt in rngd_rdrand.c but did not update rngd_jitter.c.
This raise the following build failure:
```
rngd_jitter.c:75:12: error: conflicting types for 'encrypt'
static int encrypt(unsigned char *plaintext, int plaintext_len, unsigned char *key,
^~~~~~~
In file included from rngd_jitter.c:27:
/home/dawncrow/buildroot-test/scripts/instance-0/output-1/host/powerpc-buildroot-linux-uclibc/sysroot/usr/include/unistd.h:1132:13: note: previous declaration of 'encrypt' was here
extern void encrypt (char *__block, int __edflag) __THROW __nonnull ((1));
^~~~~~~
Makefile:770: recipe for target 'rngd-rngd_jitter.o' failed
```
Fixes:
- http://autobuild.buildroot.org/results/0ca6bf16e3acbc94065b88c4442d6595424b77cb
Signed-off-by: …
> rngd_jitter: disambiguate call to encrypt

- .travis.yml
Travis CI supports s390x and ppc64le now. It would be nice to test on those platforms.
If any issues come up with the ppc64le build in future, feel free to tag me in and I'll have a look - I have access to ppc64le systems at work. I can also help find a s390x person if that goes wrong at all.
> Travis CI: test on ppc64le and s390x

- rngd_linux.c
The Linux Random Number Generator (lrng) returns the number of bytes as
the result of the RNDADDENTROPY ioctl instead of 0. This causes
rng-tools to report an error like this:
RNDADDENTROPY failed: Success
After so many failures, rng-tools will exit and stop adding entropy and
exit.
A positive ioctl return value is not indicative of an explicit error and
limiting the range of error return values to negative values will fix
this issue and allow rng-tools to support kernels using either crng or
lrng.
> Fix RNDADDENTROPY ioctl error for lrng

- rngd_jitter.c
As discussed in #98,
- set O_NONBLOCK correctly and
- set O_NONBLOCK later
Closes #98
> rngd_jitter initialization fixes

- rngd.h
Debug logs were only controlled by --debug flag while in --foreground
mode.  In --daemon mode /var/log/message got stuffed with details of
entropy pool refilling, which is useless in production, and hamful
when log rotation then gets rid of the more useful logs.  This is
especially true for embedded systems.
This change makes the two modes consistently only produce debug logs when
--debug is specified.
Signed-off-by: Yann Dirson <yann@blade-group.com>
> rngd: fix --debug to also filter syslog() calls

- rngd.c
Before this commit, I noticed `use_aes` was showing up under rtlsdr
options, even though this isn't a listed option. On a different (older)
build, it was two other rogue options- `engine_path` and `chunk_size`.
$ ./rngd -O rtlsdr
Available options for RTLSDR software defined radio generator (rtlsdr)
key: [device_id]	default value: [0]
key: [freq_min]	default value: [90000000]
key: [freq_max]	default value: [110000000]
key: [sample_min]	default value: [1000000]
key: [sample_max]	default value: [2800000]
key: [use_aes]	default value: [1]
Without the `key = null` value at the end of the array, we were
combining options from multiple entropy sources. After adding the null
value, the options list is working as expected:
$ ./rngd -O rtlsdr
Available options for RTLSDR software defined radio …
> Fix listing of rtlsdr options

- rngd.c
Default watermark level is 3/4 of available poolsize.
Signed-off-by: Tomas Melin <tomas.melin@vaisala.com>
> rngd: Fix documentation on default watermark

- rngd_rtlsdr.c
I use fedora which compiles rng-tools with their "hardening" build options, including a stack smashing detection.
Without this patch I get the following (using -d -f flags):
```
[rtlsdr]: Setting frequency to 96930886
Exact sample rate is: 2036915.046872 Hz
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
In the great tradition of security software, after finding the culprit, I cut-n-pasted the solution from this man page.  It seems correct.
https://linux.die.net/man/3/evp_encryptfinal_ex
> Allow enough space in output buffer for additional block

- fips.c
There were two (related) bugs in the Runs test that this patch fixes.
The first is it was not handling the special case of ctx->rlength == -1
so if the first bit of a block was not equal to ctx->last_bit (which is
either carried over 'uselessly' from the previous block or set to 0 for
the very first bit of a testing session, but either way is 'random' at
the start of a new block), then it will try to record that event into
ctx->runs[-1 + (6 * ctx->current_bit)].  Which in the 'best' case, will
record it as a run of 0's when it should have been a run of one 1's,
and in the worst case will instead increment ctx->poker[15] (when the
fips_ctx_t struct isn't padded between those two fields).
In any reasonable length run it will hit both cases and break both the
Runs test and the Poker test …
> Fix the broken FIPS 140-2 runs test.

- rngd_linux.c
When compiling with clang(-9) there are a couple of warnings. This fixes one of them.
> Fix use of GNU old-style field designator extension warning.

- rngd_jitter.c
rngd_jitter.c: In function 'xread_jitter':
rngd_jitter.c:146:48: warning: format '%d' expects argument of type 'int',
but argument 4 has type 'ssize_t' {aka 'long int'} [-Wformat=]
It appears this issue was introduced as part of PR #94.
> Fixes warning while compiling rngd_jitter.c

- rngd.8.in
per rngd.c source and functionality, the parameter is --force-reseed with a dash not an underscore.
updated man page accordingly
> man page fix: force-reseed

- .travis.yml
- Makefile.am
- configure.ac
- rngd_entsource.c
- rngd_nistbeacon.c
We are linking the whole libsysfs for just one read. Replace it with
a standard read() and remove libsysfs from requirements. This requires
an update of distribution's packaging and testing, such as rng-tools.spec
file for the rpmbuild.
> Stop using libsysfs and drop it

- rngd.c
Prevent messing "None" status message with next section header:
"[...]
Entropy sources that are available but disabled
NoneAvailable and enabled entropy sources:
4: NIST Network Entropy Beacon (nist)
[...]"
Signed-off-by: Nikolai Kostrigin <nickel@altlinux.org>
> Improve rngd console output readability

- Makefile.am
- ossl_helpers.c
- ossl_helpers.h
- rngd_darn.c
- rngd_jitter.c
- rngd_nistbeacon.c
- rngd_rdrand.c
- rngd_rtlsdr.c
Followup on comments in https://github.com/nhorman/rng-tools/pull/128
This moves the openssl code that is duplicated in several sources
to some helpers. This also fixes the use of "strlen" on raw random
data which probably didn't do what someone thought it did ...
Note: rtlsdr could probably use the random key generation helper, but
for now I have, I think, kept the code mostly equivalent
> Create helpers for openssl AES use

- Makefile.am
- configure.ac
- rngd.8.in
- rngd.c
- rngd_entsource.h
- rngd_rndr.c
This adds support for the RNDR instruction as an entropy source
when available.
There should be no need to run it through AES.
Tested using qemu
Signed-off-by: Benjamin Herrenschmidt <benh@amazon.com>
> Add support for ARM v8.5A "rndr" instruction

- .gitignore
- configure.ac
- contrib/Makefile.am
Hi @nhorman 
here's a bunch of fixes from Gentoo that we'd like to get merged so we don't have to carry patches downstream.
1. Use `AM_PROG_AR` over `AC_CHECK_TOOLS`
* `AM_PROG_AR` is the canonical way to detect the archiver
and includes workarounds for Cygwin.
2. Build `randstat` binary
3. `AC_CANONICAL_TARGET` -> `AC_CANONICAL_HOST`
* `AC_CANONICAL_TARGET` is the type of system for which code
will be produced, not on which it will run. This is a common
confusion with Autoconf's target triplet.
> Gentoo fixes

- rngd.c
- rngd_linux.c
- rngd_linux.h
```
We want to log errors in default_watermark(), so actually we should not
call it before logging is initialized, i.e. before processing command
line switches and setting am_daemon. With that, default_watermark() is
less needed. Adjust the code by merging it into init_kernel_rng() which
is called exactly after logging is initialized and "-l" case is handled.
Also use LOG_DEBUG priority for informational messages about entropy pool.
Initialize arguments->fill_watermark with -1 so we can distinguish cases
when watermark was or was not set by a command line switch.
Signed-off-by: Vladis Dronov <vdronov@redhat.com>
```
> Rewrite init_kernel_rng() to ensure proper logging

- rngd_jitter.c
```
Per my understanding, these are important changes which
should be included to the `onecpu` branch before it gets
merged to the `master`. A build and tests are fine.
- Adjust the main check condition
- Adjust a type of a variable for the sysconf() result
- Add some code for errors and corner cases handling
- Adjust a return code so it matches a jitter library one
(this is needed for some future improvement I'm thinking of)
- Add some spaces and new lines for a better looking code
```
> Additions and fixes for the CPU detection code

- configure.ac
@nhorman I forgot to add the second `test` when removing the obsolete `-o` construct
> configure.ac: Add missing `test`

- rngd_nistbeacon.c
Vladis pointed out here:
https://github.com/nhorman/rng-tools/issues/141
That we had a potential null deref in nistbeacon, that wasn't easily
fixed, and thei is the best way I can come up with to address it
Basically, when we parse a nist json block returned from a server, we
need to be aware that some memory allocations that occur in the process
might fail. If they do, we should abort the curl_easy_perform operation
so that the calling fuction knows that the block is invalid. To do that
I have to check the return code of every element parser we have (which
we use several times).  Thats alot of extra if(rc){return 0} code, so
I'm codifying it in a variadic macro that returns if the call fails
yes, I'm returning in a macro. Yes, thats ugly.  And yes, there is a
huge comment warning all who …
> Fix an ugly potential null deref

- rngd_jitter.c
Enclose `soft_timer` definition in `#ifndef HAVE_JITTER_NOTIME` the same
way as `soft_timer` usage is enclosed to avoid a compiler warning:
```
rng-tools-6.13/rngd_jitter.c:335:13: warning[-Wunused-variable]:
unused variable 'soft_timer'
```
Signed-off-by: Vladis Dronov <vdronov@redhat.com>
> Fix an unused variable warning

- rngd_jitter.c
To improve reliability of daemon shutdown by making sure the foreground
thread is the thread catching SIGINT and friends.
Explanation:
I'm still experiencing random freeze ups with rngd (>=5.9) on one of my embedded targets.
(Adding the full 90s systemd default timeout to a reboot.)
Disabling the jitter entropy source (-x jitter) seemed to solve the freeze ups.
Analyzing the problem I found it difficult to figure out what happens in which order
because I cannot say which of the running threads actually catches the SIGINT
and hence I decided to block SIGINT in the jitter tasks and thereby making sure
the shutdown magic starts in a more predictable manner.
> Block termination signals for the jitter tasks

- rngd_jitter.c
prototype passes pthread_t, not *pthread_t
> Fix arg 1 of pthread_setaffinity_np

- configure.ac
This will properly set the PCKS11 library search path for armv6l devices
> Add armv6l to list of pkcs11 detected arches

- rngd.8.in
- rngd.c
The man page was out of date, specifying -V as the man page version
flag, when It should be -v.  Also, the arg parser wasn't handling those
options well, as it was returning an error for those valid options.  Fix
that up to just exit cleanly after printing the version info
> Fix up version option handling

- configure.ac
Theres no great way to detect if jitterentropy has the internal timer
feature enabled so we have to look for a function that is only defined
when it is enabled
> Adjust jitterentropy detection to look for the settick function

- rngd_darn.c
And brush up code a bit. Unused variables are reported by gcc as:
```
rngd_darn.c: In function 'init_openssl':
rngd_darn.c:68:13: warning: unused variable 'i' [-Wunused-variable]
68 |         int i;
rngd_darn.c: In function 'xread_darn':
rngd_darn.c:163:19: warning: unused variable 'darn_ptr' [-Wunused-variable]
163 |         uint64_t *darn_ptr =(uint64_t *)buf;
```
> Drop unused variables

- Makefile.am
- darn_impl.c
- rngd_darn.c
The PPC64 DARN instruction is defined in ISA 3.0 which is for Power9 CPUs.
Power8 CPUs are ISA 2.07 and thus do not support DARN. Recently gcc has
limited the DARN instruction to power9 target only. Build a code with DARN
in a separate library with special compile flags.
Also add a missing check for get_darn() return value as in other places.
> Build Power9 code separately

- tests/rngtestjitter.sh
Seems the current 15 second timeout is causing occasional false failures
after recent changes.
> extend rngtestjitter timeout to a 30 second

- configure.ac
Fix the following build failure on aarch64 without `sys/auxv.h` (e.g. on uclibc) raised since version 6.13 and https://github.com/nhorman/rng-tools/commit/9070a04adfcd21ec3839ee8ff190e7130ccd5c9b:
```
rngd_rndr.c:34:10: fatal error: sys/auxv.h: No such file or directory
34 | #include <sys/auxv.h>
|          ^~~~~~~~~~~~
```
The same issue could be raised on powerpc64le since version 6.11 and https://github.com/nhorman/rng-tools/commit/ade348cdb90c25b44b203fd4e9c33ec4bccff323
Fixes:
- http://autobuild.buildroot.org/results/41d5ab9e67eb0d8af8d789fc94d4366f130a7fb2
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix build without sys/auxv.h

- configure.ac
- rngd_qrypt.c
Use visibility of jent_notime_settick() to detect if jitterentropy library is built with internal timers. The code related is:
```
[ src/jitterentropy-timer.h ]
#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER
int jent_notime_settick(struct rand_data *ec);
#else /* JENT_CONF_ENABLE_INTERNAL_TIMER */
static inline int jent_notime_settick(struct rand_data *ec)
{ (void)ec; return 0; }
#endif /* JENT_CONF_ENABLE_INTERNAL_TIMER */
```
Fix couple of whitespace and unused variable issues to please code scanners.
Thanks Neil for qcrypt, this looks like a great feature!
> configure.ac: fix jitterentropy internal timers detection

- rngd.c
As buffer size in do_loop() is FIPS_RNG_BUFFER_SIZE, so the random_step should not bigger. If random_step > FIPS_RNG_BUFFER_SIZE,  update_kernel_random() will not write any date.
Signed-off-by: lvgenggeng <lvgenggeng@uniontech.com>
> Fix random_step boundary

- rngd.c
When -i used, the fips_run_rng_test() should not be called in update_kernel_random().
Signed-off-by: lvgenggeng <lvgenggeng@uniontech.com>
> Fix ignorefail

- rngd.8.in
- rngd_pkcs11.c
Link: https://bugzilla.redhat.com/show_bug.cgi?id=1845854
> Adjust error message when pkcs11 engine is not installed

- Makefile.am
- rngd.8.in
- rngd.c
- rngd.h
- rngd_entsource.h
- rngd_namedpipe.c
Reads entropy from a named pipe (aka FIFO). Another program, for example a driver reading and preparing data from an external hardware RNG, is expected to feed entropy into this named pipe. Should the named pipe be closed, rngd will try to reopen it.
This is option 1 as discussed in #197.
> add "namedpipe" entropy source

- rngd.8.in
- rngd.c
- rngd.h
The entropy sources nist, jitter and pkcs11 are considered to be slow in providing entropy. By default their data is only used after all other sources failed to provide valid entropy a 100 times over. With this option rngd always tries to gather entropy from these sources too.
Having this option is useful when you want to feed the kernel data from a mix of as many independent sources as possible. The concern of for example jitter being too slow to supply a sufficient amount of entropy data is only relevant when rngd needs to supply entropy to the kernel often and in short order. With modern kernels not signaling a low watermark anymore and thus only the known force-reseed time is used, you can ensure that jitter will be able to provide enough data at configuration time.
When comparing the …
> add --use-slow-sources option

- configure.ac
Without the surrounding `[]`, m4 drops the inner `[]`, treating, `argv[]` as `argv`.  This results in an incorrect argument type for `argp_parse`, causing the probe to fail with future compilers due to type error.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> configure: Fix m4 quoting issue in libargp probe

- rngd.c
- rngd.h
Before this patch entropy data was gathered from one source, fed to the kernel, then the next source was gathered, fed, and so on.
With the default config on a modern kernel this lead to one source being used for 195 minutes before switching to the next source. Should one source not be as random as expected, the impact of this problem can be reduced by mixing the bad entropy with data from other sources. The long usage time of 195 minutes for one source didn't facilitate this well.
This patch changes this behavior and first gathers data from each enabled source and checks it. then a byte from each valid source block is taken in turn until the block to feed to the kernel (random_step) is filled. This mixed data is then fed to the kernel.
This fixes issue #201
> mix data fed to the kernel byte-wise from multiple sources

- rdrand_asm.S
Add endbr64/endbr32 instruction to a function prologue. This enables IBT (Indirect Branch Tracking) feature of the Intel CET (Control-flow Enforcement Technology). All the calls and jumps in this assembly code are direct. Only functions can potentially be called indirectly. So adjusting a function prologue is enough. Add a section to indicate that this code supports IBT to linkers and security analysers.
> Add Intel CET IBT instrumentation to assembly code

- rngtest.1.in
> Fix typo in man page

- .gitignore
- configure.ac
- rngd.service.in
Ideally we'd substitute the value of `sbindir` here, but autoconf makes this a much more complicated task requiring additional make targets which I have not been able to get to work.
As such, this doesn't have complete compatibility-- if `$exec_prefix` is different to `$prefix`, or `$sbindir` is defined as something esoteric, things might not work.
Still, this covers the majority of cases.
> Generate rngd.service to match directory rngd was installed into
